# Generated by Django 4.1.2 on 2022-10-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='institution_number',
            new_name='inst_num',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='transit_number',
            new_name='transit_num',
        ),
        migrations.AddField(
            model_name='branch',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
