# Generated by Django 4.1.2 on 2022-10-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(default='admin@utoronto.ca', max_length=254),
        ),
    ]
